### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by haythemd** [ecome-earth/MyFarm#4]
### Feature Requests & Improvements
This thread is for brainstorming and discussing ideas to improve the app. Feel free to leave a comment below with your suggestion!

**Please note:** While we can't guarantee all suggestions will be implemented, we'll review them carefully and consider them for future development.

To help us prioritize your suggestion, please consider including:

A clear and concise description of your idea.
The benefit this improvement would bring to the app and its users.
Any relevant details, screenshots, or mockups (optional).
We'll keep an eye on this thread and may create separate issues for specific suggestions that gain traction or require further discussion.

**Thank you for your contribution!**

**Comment by MouyouMoos** [comment]
put this issue description in the milestone description of Improvements
